CREATE TABLE user(
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    registration VARCHAR(255) UNIQUE NOT NULL,
    role VARCHAR(255)NOT NULL
);